services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
    ports:
      - "9090:9090"
    networks:
      - observability-net
    depends_on:
      - alertmanager
 
  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - observability-net
 
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=info'
    networks:
      - observability-net
    restart: unless-stopped

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - observability-net
    restart: unless-stopped

networks:
  observability-net:
    external: true
    name: observability_observability-net