upstream dvwa {
    server dvwa:80;
}

server {
    listen 80;
    server_name _;
    location / {
        proxy_pass http://dvwa;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log warn;
    }
    location /nginx_status {
        stub_status on;
        access_log off;
        allow 172.0.0.0/8;
        allow 192.168.0.0/16;
        allow 127.0.0.1;
        deny all;
    }
}