[PARSER]
    Name          nginx
    Format        regex
    Regex         ^(?<client_ip>[^ ]*) - (?<remote_user>[^ ]*) \[(?<timestamp>[^\]]*)\] "(?<http_method>[^ ]*) (?<request_uri>[^ ]*) HTTP/(?<http_version>[^"]*)" (?<status_code>[^ ]*) (?<bytes_sent>[^ ]*) "(?<http_referer>[^"]*)" "(?<user_agent>[^"]*)"
    Time_Key      timestamp
    Time_Format   %d/%b/%Y:%H:%M:%S %z